# Generated by Django 4.2.1 on 2023-06-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0002_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='genero',
            field=models.ManyToManyField(to='cine.genre'),
        ),
    ]
