# Generated by Django 4.2.1 on 2023-06-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0003_pelicula_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(help_text='Ingresar genero: ', max_length=100),
        ),
    ]
