# Generated by Django 4.2.1 on 2023-06-02 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0004_alter_genre_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='summary',
            field=models.TextField(default='', help_text='Resumen de la pelicula', max_length=100),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(help_text='Ingresar genero ', max_length=64),
        ),
    ]
